<?php

namespace Database\Seeders;

use App\Models\Blog;
use App\Models\SeoMeta;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class DatabaseSeeder extends Seeder
{
    public function run(): void
    {
        // Admin user
        User::updateOrCreate(
            ['email' => 'admin@7xbasket.com'],
            [
                'name'     => 'Admin',
                'email'    => 'admin@7xbasket.com',
                'password' => Hash::make('Admin@123'),
                'role'     => 'admin',
            ]
        );

        // Sample blogs
        $blogs = [
            ['title' => 'Why Grocery Franchise is the Best Business in 2025', 'excerpt' => 'Discover why grocery franchises are booming and how 7x Basket leads the way.', 'content' => '<h2>Why Grocery is a Recession-Proof Business</h2><p>The grocery industry is one of the most resilient sectors in the economy. People always need food, making it a stable investment regardless of economic conditions.</p><p>With 7x Basket, you get a proven model, brand recognition, and full operational support to launch your own store.</p><h2>What 7x Basket Offers Franchise Partners</h2><ul><li>Zero Royalty Model</li><li>Complete Store Setup Support</li><li>Tech-Enabled Billing & Inventory</li><li>High-Margin Product Range</li><li>Dedicated Franchise Manager</li></ul>', 'category' => 'Business', 'tags' => 'franchise, grocery, business, investment', 'author' => '7x Basket Team', 'is_published' => true, 'published_at' => now()->subDays(2)],
            ['title' => 'How to Choose the Right Location for Your Grocery Store', 'excerpt' => 'Location is everything. Learn how to pick the perfect spot for your 7x Basket franchise.', 'content' => '<h2>Why Location Matters</h2><p>Choosing the right location can make or break your grocery franchise. Key factors include foot traffic, nearby residential density, parking availability, and competition analysis.</p><p>Our team provides a full location assessment before you sign any agreement.</p>', 'category' => 'Tips', 'tags' => 'location, store, tips, franchise', 'author' => '7x Basket Team', 'is_published' => true, 'published_at' => now()->subDays(5)],
            ['title' => '5 Reasons to Invest in 7x Basket Franchise Today', 'excerpt' => 'From low investment to high ROI, here are 5 compelling reasons to join 7x Basket.', 'content' => '<h2>Top Reasons to Invest</h2><p>1. <strong>Low Entry Cost</strong> - Start with as little as ₹5 Lakhs.</p><p>2. <strong>Brand Support</strong> - Full marketing and branding assistance.</p><p>3. <strong>Training</strong> - Comprehensive onboarding program.</p><p>4. <strong>Supply Chain</strong> - Direct sourcing for better margins.</p><p>5. <strong>Technology</strong> - POS and inventory management included.</p>', 'category' => 'Investment', 'tags' => 'investment, ROI, franchise benefits', 'author' => '7x Basket Team', 'is_published' => true, 'published_at' => now()->subDays(8)],
            ['title' => 'Understanding the Zero Royalty Franchise Model', 'excerpt' => 'What does zero royalty really mean for your business? We break it down simply.', 'content' => '<h2>What is Zero Royalty?</h2><p>Most franchise models charge a monthly royalty fee — typically 5–8% of your revenue. At 7x Basket, we charge zero royalty. You keep every rupee you earn.</p><h2>How We Make Money Instead</h2><p>We earn through the supply chain by sourcing products at scale and passing savings to partners. This aligns our interests with yours — the more you sell, the better for everyone.</p>', 'category' => 'Business', 'tags' => 'royalty, franchise model, profit', 'author' => '7x Basket Team', 'is_published' => true, 'published_at' => now()->subDays(12)],
            ['title' => 'Mini Store vs Super Store vs Hyper Store: Which is Right for You?', 'excerpt' => 'Compare all three 7x Basket store formats and find the best fit for your investment.', 'content' => '<h2>Mini Store (300–500 sq ft)</h2><p>Perfect for residential colonies and small markets. Investment starts at ₹5 Lakhs. Ideal for first-time entrepreneurs.</p><h2>Super Store (800–1200 sq ft)</h2><p>Our most popular format. Serves a wider product range and higher footfall. Investment ₹10–15 Lakhs.</p><h2>Hyper Store (2000+ sq ft)</h2><p>For high-traffic commercial areas. Full product range with premium margins. Investment ₹20–30 Lakhs.</p>', 'category' => 'Tips', 'tags' => 'store format, mini, super, hyper', 'author' => '7x Basket Team', 'is_published' => true, 'published_at' => now()->subDays(15)],
            ['title' => 'How Technology is Transforming Grocery Retail in India', 'excerpt' => 'From POS systems to inventory apps, see how tech is changing the game for franchise owners.', 'content' => '<h2>The Tech Revolution in Grocery</h2><p>Modern grocery stores are no longer just shelves and counters. Cloud-based POS systems, real-time inventory tracking, and customer loyalty apps are now standard tools for successful franchise owners.</p><p>7x Basket provides all of this from day one — no technical knowledge required.</p>', 'category' => 'Technology', 'tags' => 'technology, POS, inventory, digital', 'author' => '7x Basket Team', 'is_published' => true, 'published_at' => now()->subDays(18)],
            ['title' => 'Success Story: How Rajesh Kumar Built a Profitable Store in 8 Months', 'excerpt' => 'A real franchise partner shares his journey from application to profitability.', 'content' => '<h2>From Employee to Entrepreneur</h2><p>Rajesh Kumar from Delhi was working a corporate job when he decided to invest in a 7x Basket Super Store. Within 8 months, his store was profitable and he had hired a team of 6 people.</p><p>"The support from the 7x Basket team was incredible. They helped me with everything from store design to staff training," says Rajesh.</p>', 'category' => 'Success Stories', 'tags' => 'success story, partner, Delhi', 'author' => '7x Basket Team', 'is_published' => true, 'published_at' => now()->subDays(20)],
            ['title' => 'The Complete Guide to FSSAI Compliance for Grocery Stores', 'excerpt' => 'Everything you need to know about food safety regulations for your franchise store.', 'content' => '<h2>What is FSSAI?</h2><p>The Food Safety and Standards Authority of India (FSSAI) regulates food businesses in India. Every grocery store must have a valid FSSAI license to operate legally.</p><h2>How 7x Basket Helps</h2><p>We handle all FSSAI documentation and compliance as part of our franchise setup process. You focus on running the store — we handle the paperwork.</p>', 'category' => 'Compliance', 'tags' => 'FSSAI, compliance, legal, food safety', 'author' => '7x Basket Team', 'is_published' => true, 'published_at' => now()->subDays(22)],
            ['title' => 'How to Manage Inventory Effectively in a Grocery Store', 'excerpt' => 'Smart inventory management tips that reduce waste and maximize your profits.', 'content' => '<h2>Why Inventory Management Matters</h2><p>Poor inventory management leads to stockouts, wastage, and lost revenue. With the right systems, you can reduce waste by up to 30% and always have the right products on the shelf.</p><h2>7x Basket Inventory Tools</h2><p>Our cloud-based inventory system tracks stock levels in real time, sends expiry alerts, and auto-generates reorder suggestions based on sales patterns.</p>', 'category' => 'Operations', 'tags' => 'inventory, management, operations, tips', 'author' => '7x Basket Team', 'is_published' => true, 'published_at' => now()->subDays(25)],
            ['title' => 'Top 10 Products That Drive the Most Revenue in Grocery Stores', 'excerpt' => 'Find out which product categories generate the highest margins for franchise owners.', 'content' => '<h2>High-Margin Categories</h2><p>Not all products are equal. Dairy, personal care, and packaged snacks typically offer the highest margins. Understanding your product mix is key to maximizing profitability.</p><p>7x Basket partners get access to 5000+ SKUs with pre-negotiated wholesale prices from top FMCG brands.</p>', 'category' => 'Business', 'tags' => 'products, revenue, margins, FMCG', 'author' => '7x Basket Team', 'is_published' => true, 'published_at' => now()->subDays(28)],
            ['title' => 'How to Market Your Grocery Store Locally', 'excerpt' => 'Practical marketing strategies to attract and retain customers in your neighbourhood.', 'content' => '<h2>Local Marketing That Works</h2><p>Digital ads, WhatsApp groups, local flyers, and loyalty programs are all effective tools for driving footfall to your store. The key is consistency and community engagement.</p><p>7x Basket handles national campaigns while you focus on local outreach with our ready-made marketing kits.</p>', 'category' => 'Marketing', 'tags' => 'marketing, local, customers, footfall', 'author' => '7x Basket Team', 'is_published' => true, 'published_at' => now()->subDays(30)],
            ['title' => 'Staff Training Best Practices for Grocery Franchise Owners', 'excerpt' => 'How to build and retain a high-performing team for your 7x Basket store.', 'content' => '<h2>Why Staff Training Matters</h2><p>Your staff are the face of your store. Well-trained employees improve customer satisfaction, reduce errors, and increase sales through better product knowledge.</p><p>7x Basket provides a structured training program covering billing, customer service, inventory management, and store hygiene standards.</p>', 'category' => 'Operations', 'tags' => 'staff, training, team, operations', 'author' => '7x Basket Team', 'is_published' => true, 'published_at' => now()->subDays(33)],
            ['title' => 'ROI Calculator: How Much Can You Earn from a Grocery Franchise?', 'excerpt' => 'Use our simple formula to estimate your monthly earnings from a 7x Basket franchise.', 'content' => '<h2>Understanding Your ROI</h2><p>Return on investment depends on store size, location, footfall, and product mix. On average, 7x Basket partners achieve 25–30% gross margins with breakeven in 6–12 months.</p><h2>Sample Calculation</h2><p>A Super Store with 300 daily customers at ₹350 average bill generates ₹31.5L monthly revenue. At 25% margin, that is ₹7.87L monthly profit.</p>', 'category' => 'Investment', 'tags' => 'ROI, calculator, earnings, profit', 'author' => '7x Basket Team', 'is_published' => true, 'published_at' => now()->subDays(36)],
            ['title' => 'Franchise vs Independent Store: Which is Better in 2025?', 'excerpt' => 'An honest comparison to help you decide between starting a franchise or going independent.', 'content' => '<h2>The Independent Store Challenge</h2><p>Running an independent grocery store means handling everything yourself — sourcing, branding, marketing, compliance, and technology. Most independent stores struggle to compete with organized retail.</p><h2>The Franchise Advantage</h2><p>A franchise gives you a proven system, brand recognition, supply chain access, and ongoing support. The risk is significantly lower and the path to profitability is faster.</p>', 'category' => 'Business', 'tags' => 'franchise vs independent, comparison, business', 'author' => '7x Basket Team', 'is_published' => true, 'published_at' => now()->subDays(40)],
            ['title' => 'How 7x Basket Supports You From Day One to Grand Opening', 'excerpt' => 'A step-by-step look at the complete support system every franchise partner receives.', 'content' => '<h2>Our End-to-End Support</h2><p>From the moment you sign the franchise agreement, our team is with you every step of the way. Site selection, store design, staff recruitment, inventory setup, POS installation, and grand opening marketing — all handled by 7x Basket.</p><p>Most stores are ready to open within 45–60 days of signing.</p>', 'category' => 'Tips', 'tags' => 'support, setup, onboarding, grand opening', 'author' => '7x Basket Team', 'is_published' => true, 'published_at' => now()->subDays(45)],
        ];

        foreach ($blogs as $blog) {
            Blog::updateOrCreate(['title' => $blog['title']], $blog);
        }

        // SEO defaults
        $seoData = [
            ['page_key' => 'home',       'title' => '7x Basket - Premium Grocery Franchise Opportunity', 'description' => 'Start your own grocery franchise with 7x Basket. Low investment, high returns, full support system.'],
            ['page_key' => 'about',      'title' => 'About Us - 7x Basket Franchise', 'description' => 'Learn about 7x Basket, our mission, vision and why we are the best grocery franchise in India.'],
            ['page_key' => 'blogs',      'title' => 'Blog - 7x Basket Franchise Insights', 'description' => 'Read the latest articles about grocery franchise, business tips and 7x Basket updates.'],
            ['page_key' => 'apply',      'title' => 'Apply for Franchise - 7x Basket', 'description' => 'Apply now to become a 7x Basket franchise partner.'],
            ['page_key' => 'contact',    'title' => 'Contact Us - 7x Basket', 'description' => 'Get in touch with the 7x Basket franchise team.'],
            ['page_key' => 'calculator', 'title' => 'Investment Calculator - 7x Basket', 'description' => 'Calculate your potential returns from a 7x Basket grocery franchise.'],
        ];

        foreach ($seoData as $seo) {
            SeoMeta::updateOrCreate(['page_key' => $seo['page_key']], $seo);
        }
    }
}
